fake_data:
  folder_path: ./sample_data/gh-archive
  num_files: 3

datalake:
  endpoint: localhost:9000
  bucket_name: gh-archive-sample-data
  folder_name: 2015-01-01-15
  access_key: minio_access_key
  secret_key: minio_secret_key