{
 "title": "Airflow Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Duration to Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_data_pipeline_clean_up_queued_duration{quantile=\"0.9\"}"
    },
    {
     "expr": "airflow_dag_data_pipeline_download_to_bronze_queued_duration{quantile=\"0.9\"}"
    },
    {
     "expr": "airflow_dag_data_pipeline_get_file_path_queued_duration{quantile=\"0.9\"}"
    },
    {
     "expr": "airflow_dag_data_pipeline_load_to_silver_queued_duration{quantile=\"0.9\"}"
    },
    {
     "expr": "airflow_dag_data_pipeline_setup_minio_queued_duration{quantile=\"0.9\"}"
    },
    {
     "expr": "airflow_dag_data_pipeline_write_tables_in_gold_queued_duration{quantile=\"0.9\"}"
    },
    {
     "expr": "airflow_task_queued_duration{quantile=\"0.9\"}"
    }
   ]
  },
  {
   "title": "Time to Load New Data to Zones",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "airflow_dag_data_pipeline_download_to_bronze_duration{quantile=\"0.9\"}"
    },
    {
     "expr": "airflow_dag_data_pipeline_load_to_silver_duration{quantile=\"0.9\"}"
    },
    {
     "expr": "airflow_dag_data_pipeline_write_tables_in_gold_duration{quantile=\"0.9\"}"
    }
   ]
  },
  {
   "title": "Airflow Running and Queued Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Airflow Queued Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Airflow Running Tasks" }
   ]
  },
  {
   "title": "Airflow Queued/Running/Deferred Slots",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "airflow_pool_queued_slots{}" },
    { "expr": "airflow_pool_running_slots{}" },
    { "expr": "airflow_pool_deferred_slots{}" }
   ]
  },
  {
   "title": "Delay Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "airflow_dagrun_first_task_scheduling_delay{quantile=\"0.9\"}"
    },
    {
     "expr": "airflow_dagrun_schedule_delay{quantile=\"0.9\"}"
    }
   ]
  }
 ]
}